2025-01-02 01:01:24,614 ERROR: Exception on /java [GET] [in C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\app.py", line 100, in java
    posts = get_posts('java')
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\app.py", line 75, in get_posts
    return sorted(posts, key=lambda x: x['date'], reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare datetime.datetime to datetime.date
2025-01-02 01:01:24,620 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\app.py:87]
2025-01-02 01:01:32,461 ERROR: Exception on /java [GET] [in C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\app.py", line 100, in java
    posts = get_posts('java')
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\app.py", line 75, in get_posts
    return sorted(posts, key=lambda x: x['date'], reverse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare datetime.datetime to datetime.date
2025-01-02 01:01:32,463 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in C:\Users\aonik\OneDrive\Projects\project-pack\projectpack001\app.py:87]
